# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160625_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='rooney', max_length=128),
        ),
    ]
