# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 14:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20160625_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='scheduled_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 6, 25, 14, 55, 8, 434013)),
        ),
    ]
