# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 06:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20160626_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='scheduled_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 6, 26, 6, 55, 34, 575282)),
        ),
    ]
