# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 09:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_password'),
        ('tasks', '0004_auto_20160627_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AlterField(
            model_name='task',
            name='scheduled_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 6, 26, 9, 10, 54, 298908)),
        ),
    ]
