# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 11:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20160627_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='scheduled_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 6, 26, 11, 34, 19, 237359)),
        ),
    ]
